# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wl@latest < Formula
  desc "waddleloop — governed multi-agent fleet orchestration (latest pointer)"
  homepage "https://github.com/askrubberduck/waddleloop"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/askrubberduck/waddleloop/releases/download/v0.1.0/waddleloop-0.1.0-darwin-amd64.tar.gz"
      sha256 "9f75f8727cdb91258265c204d6b511b4f0b11b1e4df8ab5a7136f484246a8994"

      define_method(:install) do
        bin.install "wl"
        bin.install "wld"
        bin.install "wl-mcp"
        bin.install "wl-web"
        bin.install "wltrust"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/askrubberduck/waddleloop/releases/download/v0.1.0/waddleloop-0.1.0-darwin-arm64.tar.gz"
      sha256 "d097ed77a219de9e7738332512373240dbd879b1b33aee963080a62ba06c8872"

      define_method(:install) do
        bin.install "wl"
        bin.install "wld"
        bin.install "wl-mcp"
        bin.install "wl-web"
        bin.install "wltrust"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/askrubberduck/waddleloop/releases/download/v0.1.0/waddleloop-0.1.0-linux-amd64.tar.gz"
      sha256 "11bcdf1c80375d7a7b045545eb147865cadc0446e50c5151810579525ad9d3c3"
      define_method(:install) do
        bin.install "wl"
        bin.install "wld"
        bin.install "wl-mcp"
        bin.install "wl-web"
        bin.install "wltrust"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/askrubberduck/waddleloop/releases/download/v0.1.0/waddleloop-0.1.0-linux-arm64.tar.gz"
      sha256 "394fefe4affa437e9670855a17f2011817634b115b071ceb1cf1e9ea41fa2b30"
      define_method(:install) do
        bin.install "wl"
        bin.install "wld"
        bin.install "wl-mcp"
        bin.install "wl-web"
        bin.install "wltrust"
      end
    end
  end

  test do
    system "#{bin}/wl", "--version"
  end
end
